spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
zuul:
  routes:
    feign:
      path: /feign/**
      serviceId: feign-comsumer
    ribbion:
      path: /ribbon/**
      serviceId: ribbon-comsumer
